### ISSUE TITLE
require mediawiki/mediawiki statement in composer.json breaks scrutinizer

### ISSUE THREAD

**Issue by oetterer** [ProfessionalWiki/Bootstrap#14]
Since _mediawiki/mediawiki_ is not a valid package name, my scrutinizer test breaks [0]. Is there a reason this was added? Can we safely remove it? If not, can somebody point me to a scrutinizer config that lets me ignore this? @JeroenDeDauw maybe?

[0] ![grafik](https://user-images.githubusercontent.com/9444462/78502741-dc9d0600-7762-11ea-82af-2d2547ee8b8e.png)

**Comment by JeroenDeDauw** [comment]
I think we can remove this since the version constraint is already specified by https://github.com/ProfessionalWiki/Bootstrap/blob/master/extension.json#L13

That'd also be in line with https://mwstake.org/mwstake/wiki/Request_for_Comment/Hybrid_extension_management, which I generally think is a good idea.

@s7eph4n will remove but pinging you so you can weigh in if you think this is a mistake. We can always revert.

**Comment by s7eph4n** [comment]
`mediawiki/mediawiki` is a virtual package added by MW during Composer runs. Itallows enforcing of version constraints _during installation_ (as opposed to _at runtime_). There are efforts at WMF to remove this virtual package "because MW does not support installation of extensions via composer", although these have been stalled for the moment [1].
So, while I still think that this virtual package has a lot of merits it is probably going to go away at some point.
For what concerns testing, you indeed have to install MW each time (or somehow assure Composer that MW is available in a compatible version). mediawiki/bootstrap is so simple, I never bothered to set up CI testing.

[1] https://gerrit.wikimedia.org/r/#/c/mediawiki/core/+/551346/

**Comment by JeroenDeDauw** [comment]
Do you think there is a big downside to just checking compatibility at `enable time` rather than also at `install time`?

**Comment by JeroenDeDauw** [comment]
After spelling that out I think I've changed my mind back to my original position. Guess I was too sleepy when I read https://mwstake.org/mwstake/wiki/Request_for_Comment/Hybrid_extension_management

Problem: without the install time check Composer will happily give you a version of the skin too new for your version of MW.

**Comment by JeroenDeDauw** [comment]
Revert in https://github.com/ProfessionalWiki/Bootstrap/pull/16

**Comment by oetterer** [comment]
> For what concerns testing, you indeed have to install MW each time (or somehow assure Composer that MW is available in a compatible version). mediawiki/bootstrap is so simple, I never bothered to set up CI testing.

Well I do build the complete MW stack on travis and ci runs smoothly. It's the code review by [scrutinizer] that fails during buildup since it checks the requirements in composer.json against packagist. Scrutinizer suggests to include a composer.lock or disabling PHP Analyzer to fix the problem, but a) I have no composer.lock with a package named _mediawiki/mediwiki_ and b) I can't find a way to disable the PHP Analyszer (which I suspect will also disable the code review).

[scrutinizer]: https://scrutinizer-ci.com/g/oetterer/BootstrapComponents/inspections/c50c80e3-fefa-43fe-a2a4-d5cbe2230152

**Comment by JeroenDeDauw** [comment]
If composer is executed inside of the MW root directory it should find `mediawiki/mediwiki` via the Composer hooks MediaWiki defines. My guess is that the CI is not running composer inside of MW. You could try changing that. Or maybe hack in a new virtual package definition into the CI build.

**Comment by s7eph4n** [comment]
Chameleon adds a "provides" clause to composer.json: https://scrutinizer-ci.com/g/ProfessionalWiki/chameleon/settings/build-config

Not nice, but works. A better approach would be to actually parse the composer.json. 
E.g. similar to https://github.com/ProfessionalWiki/SimpleBatchUpload/blob/master/tests/setup/fix-composer.php

**Comment by oetterer** [comment]
> Chameleon adds a "provides" clause to composer.json: https://scrutinizer-ci.com/g/ProfessionalWiki/chameleon/settings/build-config

Could you provide that build-config, please. I have no access to scrutinizers settings for the chameleon extensions. :-(

**Comment by s7eph4n** [comment]
Sorry. Here they are (only the `build` part is relevant): 

``` yaml
build:
    nodes:
        analysis:
            dependencies:
                before:
                    - mv composer.json composer.json.orig
                    - 'sed "s/^{$/{\"provide\":{\"mediawiki\\/mediawiki\": \"1.31\"},\\n/" < composer.json.orig > composer.json'
                    - composer config minimum-stability dev
            tests:
                override:
                    - php-scrutinizer-run
                    -
                        command: phpcs-run
                        use_website_config: true
                    - js-scrutinizer-run

checks:
    php: true
    javascript: true

coding_style:
    php:
        indentation:
            general:
                use_tabs: true
            switch:
                indent_case: false
        spaces:
            around_operators:
                concatenation: true
            within:
                brackets: true
                array_initializer: true
                grouping: true
                function_call: true
                function_declaration: true
                if: true
                for: true
                while: true
                switch: true
                catch: true
        braces:
            classes_functions:
                class: end-of-line
                function: end-of-line
                closure: end-of-line
            if:
                opening: end-of-line
            for:
                opening: end-of-line
            while:
                opening: end-of-line
            do_while:
                opening: end-of-line
            switch:
                opening: end-of-line
            try:
                opening: end-of-line
        upper_lower_casing:
            keywords:
                general: lower
            constants:
                true_false_null: lower

tools:
    php_sim: true
    php_analyzer: true
    external_code_coverage:
        timeout: 1800    # Timeout in seconds.
    js_hint: true
    php_mess_detector: true
    sensiolabs_security_checker: true
filter:
    excluded_paths:
        - 'tests/*'
        - 'resources/js/sticky-kit/*'
```
